version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "13:00"
      timezone: "Asia/Almaty"
    assignees:
      - "thekhegay"
    labels:
      - "npm"
      - "deps"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "13:00"
      timezone: "Asia/Almaty"
    assignees:
      - "thekhegay"
    labels:
      - "github-actions"
      - "deps"
