version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "13:00"
      timezone: "Asia/Almaty"
    assignees:
      - "thekhegay"
    labels:
      - "npm"
      - "deps"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
